### ISSUE TITLE
Generated swagger is improperly including conditionally required properties

### ISSUE THREAD

**Issue by andrewryan1906** [Twipped/joi-to-swagger#40]
I'm using the .when function to make certain fields required only when other fields have a specific value. In my use case, I use the same swagger for CREATEing an object as I do for UPDATEing it, but the 'id' property is only required on UPDATE... so I use the sys_version (which is a DB timestamp field) to be able to tell. Thus I have a Joi property that looks like:

`id: Joi.string().description('The unique, string identifier of this invoice').when('sys_version', {is: Joi.number().greater(0).required(), then: Joi.required())`

The problem is, the Swagger that is generated is including the 'id' as a required property as if I had written the schema with a Joi.required(). 

This is undesirably behavior - I'd like the Joi schema to not include conditionally required properties as required in the Swagger output.

Thanks!
Andrew

**Comment by Twipped** [comment]
I _think_ I know how to fix for this, but it's gonna be a breaking change, so I want to sit on it for a bit.

This issue has made me aware that I'm not really handling `alternatives` schema types correctly, because I should be mixing the `then` and `otherwise` results into the base type (currently it uses one or the other, completely ignoring the base type), and generating a `oneOf` with both outcomes instead of just using the first outcome with an ability to override.

First I need to figure out how to do that mixdown.

**Comment by Mairu** [comment]
The handling of alternatives was changed in version 4.
